[project]
name = "myproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sisi1214", email = "sitoutinnok@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.128.8",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
myproject = "myproject:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
